### ISSUE TITLE
private mode does not work

### ISSUE THREAD

**Issue by julienmalik** [YunoHost-Apps/gogs_ynh#16]
If I choose to be *not* public, then accessing the page while loggued in the sso gets me a blank page (with a 500 Internal Error in the logs).

just switching to public, and running an upgrade, and it works.

I guess the private mode has an issue (no idea why)

**Comment by dattaz** [comment]
I confirme i got the same problem.
Anyway this is what i get when i try `git push -u origin master` : 
`fatal: https://[domain]/gogs/[user]/[reponame].git/info/refs not valid: is this a git repository?`

Nothing in nginx log, nothing in gogs log, status code of request is 302.

**Comment by mbugeia** [comment]
@dattaz I think this is a different issue. What you described is an undocumented but normal behavior you can find my explanation here: https://github.com/YunoHost-Apps/gogs_ynh/issues/8#issuecomment-264646461 But you should be able to use git clone/push/.. by ssh instead of https.
This can't really by bypassed because we will have to unprotect domain/gogs_path/* and this will basically make the app public.

@julienmalik Unfortunately I didn't test very well the private mode. If you were to reproduce the issue, you can probably see the real go error in the service log `journalctl -u gogs.service`

**Comment by nemsia** [comment]
Hello,
I have disable private mode on my gogs and i enable ```REQUIRE_SIGNIN_VIEW    = true``` in /opt/gogs/custom/conf/app.ini.
It made the app private and i can pull and push on https.

**Comment by Josue-T** [comment]
Hello,
Thanks @nemsia , I have written something here : https://forum.yunohost.org/t/gogs-redirect-fatal-unable-to-update-url-base-from-redirection/3117/6 but it was not the best solution. So I think I will implement your idea to fix this issue.

**Comment by Josue-T** [comment]
Hello,

I have fixed this in the [testing branch](https://github.com/YunoHost-Apps/gogs_ynh/tree/testing). You can try it if you want.

**Comment by nemsia** [comment]
Hello,
Testing branch solution work very well for me,
Thank you.

**Comment by Josue-T** [comment]
I close this issue.
I you encounter any problem about that please reopen it.
