### ISSUE TITLE
Update to 0.11.29

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/gogs_ynh#35]
Please update the app to version 0.11.29 https://github.com/gogits/gogs/releases

**Comment by Josue-T** [comment]
We probaly need to solve the pull request https://github.com/YunoHost-Apps/gogs_ynh/pull/29 to be able to upgrade to 0.11.29.

**Comment by a-r-db** [comment]
I currently change the values so that [this version was installed. v0.11.33](https://github.com/gogits/gogs/releases/tag/v0.11.33)  and it's completely functional.
I had problems with v0.11.34
I will try to upgrade again sometime if I can.
Just wanted to say great application and thanks for packaging it!

**Comment by Josue-T** [comment]
Upgrading to 0.11.34 is not possible now. There are an issue https://github.com/gogits/gogs/issues/4894
So it's the reason because I didn't realased the package with the upstream version 0.11.34

**Comment by Josue-T** [comment]
Updated to 0.11.43
